/**
 * Centralized Icon Library
 * Exports all lucide-react icons used throughout the application
 * This allows modules to import only what they need
 */

export {
  // Navigation & Layout
  LayoutDashboard,
  Menu,
  ChevronDown,
  ChevronRight,
  ArrowRight,
  X,
  Plus,
  Grid,
  List,
  
  // Users & People
  Users,
  User,
  UserPlus,
  
  // AI & Automation
  Bot,
  Workflow,
  Zap,
  
  // Communication
  MessageSquare,
  MessageCircle,
  Mail,
  Phone,
  PhoneCall,
  Radio,
  Video,
  
  // Content & Media
  PenTool,
  FileText,
  Image,
  UploadCloud,
  Paperclip,
  Download,
  
  // Business & Operations
  ShoppingCart,
  CreditCard,
  DollarSign,
  Receipt,
  Tag,
  Briefcase,
  
  // Organization
  GitMerge,
  Pipeline,
  CheckSquare,
  ListChecks,
  Clock,
  Calendar,
  CalendarDays,
  CalendarIcon: Calendar,
  
  // Web & Integration
  Globe,
  Link,
  Webhook,
  Server,
  Chrome,
  Package,
  Terminal,
  MessageSquareCode,
  Code,
  
  // Security & Settings
  Settings,
  Shield,
  ShieldCheck,
  Lock,
  Key,
  EyeOff,
  
  // Status & Feedback
  CheckCircle,
  AlertCircle,
  AlertOctagon,
  
  // Media Controls
  Play,
  StopCircle,
  Activity,
  
  // Search & Filter
  Search,
  Filter,
  Crosshair,
  
  // UI Elements
  Layout,
  Box,
  Columns,
  Layers,
  Table,
  
  // Text Formatting
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  
  // Other
  Power,
  Copy,
  Edit2,
  Trash2,
  MoreHorizontal,
  LogOut,
  FileInput,
  MapPin,
  Smartphone,
  Bell,
  Bookmark,
  Flag,
  TrendingUp,
  GripVertical,
  AtSign,
  Hash,
  MousePointer,
  Cpu,
  Target,
  ExternalLink,
  Save,
} from 'lucide-react';

/**
 * Icon Library Object
 * For backward compatibility with existing code that uses ICON_LIBRARY object
 */
import * as IconsModule from 'lucide-react';

export const ICON_LIBRARY = {
  LayoutDashboard: IconsModule.LayoutDashboard,
  Users: IconsModule.Users,
  Bot: IconsModule.Bot,
  Workflow: IconsModule.Workflow,
  Radio: IconsModule.Radio,
  CalendarIcon: IconsModule.Calendar,
  MessageSquare: IconsModule.MessageSquare,
  PenTool: IconsModule.PenTool,
  GitMerge: IconsModule.GitMerge,
  FileText: IconsModule.FileText,
  ShoppingCart: IconsModule.ShoppingCart,
  Globe: IconsModule.Globe,
  Phone: IconsModule.Phone,
  Settings: IconsModule.Settings,
  Video: IconsModule.Video,
  CreditCard: IconsModule.CreditCard,
  Zap: IconsModule.Zap,
  Shield: IconsModule.Shield,
  Tag: IconsModule.Tag,
  Layout: IconsModule.Layout,
  EyeOff: IconsModule.EyeOff,
  Activity: IconsModule.Activity,
  Crosshair: IconsModule.Crosshair,
  Box: IconsModule.Box,
  CheckSquare: IconsModule.CheckSquare,
  Key: IconsModule.Key,
  Lock: IconsModule.Lock,
  Briefcase: IconsModule.Briefcase,
  FileInput: IconsModule.FileInput,
  Webhook: IconsModule.Webhook,
  Link: IconsModule.Link,
  Power: IconsModule.Power,
  Download: IconsModule.Download,
  Package: IconsModule.Package,
  Clock: IconsModule.Clock,
  Copy: IconsModule.Copy,
  Server: IconsModule.Server,
  Chrome: IconsModule.Chrome,
  PhoneCall: IconsModule.PhoneCall,
  Paperclip: IconsModule.Paperclip,
  CheckCircle: IconsModule.CheckCircle,
  AlertCircle: IconsModule.AlertCircle,
  Play: IconsModule.Play,
  StopCircle: IconsModule.StopCircle,
  UploadCloud: IconsModule.UploadCloud,
  User: IconsModule.User,
  Bell: IconsModule.Bell,
  Smartphone: IconsModule.Smartphone,
  MapPin: IconsModule.MapPin,
  Receipt: IconsModule.Receipt,
  CardIcon: IconsModule.CreditCard,
  Cpu: IconsModule.Cpu,
  Target: IconsModule.Target,
  ShieldCheck: IconsModule.ShieldCheck,
  Terminal: IconsModule.Terminal,
  MessageSquareCode: IconsModule.MessageSquareCode,
  Layers: IconsModule.Layers,
  AlertOctagon: IconsModule.AlertOctagon,
  Bookmark: IconsModule.Bookmark,
  Flag: IconsModule.Flag,
  TrendingUp: IconsModule.TrendingUp,
  DollarSign: IconsModule.DollarSign,
  GripVertical: IconsModule.GripVertical,
  Type: IconsModule.Type,
  AlignLeft: IconsModule.AlignLeft,
  ListChecks: IconsModule.ListChecks,
  CalendarDays: IconsModule.CalendarDays,
  ActivityIcon: IconsModule.Activity,
  Hash: IconsModule.Hash,
  AtSign: IconsModule.AtSign,
  MousePointer: IconsModule.MousePointer,
  Image: IconsModule.Image,
  Table: IconsModule.Table,
  Code: IconsModule.Code,
  AlignCenter: IconsModule.AlignCenter,
  AlignRight: IconsModule.AlignRight,
  Bold: IconsModule.Bold,
  Italic: IconsModule.Italic,
  Underline: IconsModule.Underline,
  ChevronDown: IconsModule.ChevronDown,
  ChevronRight: IconsModule.ChevronRight,
  Search: IconsModule.Search,
  Plus: IconsModule.Plus,
  ExternalLink: IconsModule.ExternalLink,
  Edit2: IconsModule.Edit2,
  X: IconsModule.X,
  List: IconsModule.List,
  Grid: IconsModule.Grid,
  UserPlus: IconsModule.UserPlus,
  Mail: IconsModule.Mail,
  MessageCircle: IconsModule.MessageCircle,
  Trash2: IconsModule.Trash2,
  MoreHorizontal: IconsModule.MoreHorizontal,
  LogOut: IconsModule.LogOut,
  Columns: IconsModule.Columns,
  Filter: IconsModule.Filter,
  ArrowRight: IconsModule.ArrowRight,
  Save: IconsModule.Save,
  Calendar: IconsModule.Calendar,
};

export default ICON_LIBRARY;
