FROM node:18-alpine AS builder

WORKDIR /app

ENV VITE_ALLOW_MULTI=true
ENV NODE_ENV=development

COPY package*.json ./
COPY package-lock.json ./
RUN npm install --include=dev

COPY . ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]