from __future__ import annotations

import copy
import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any


SCHEMA_DIR = Path(__file__).with_name("schemas")
TENANT_SETTINGS_SCHEMA_PATH = SCHEMA_DIR / "tenant-settings.schema.json"
TENANT_BLUEPRINT_SCHEMA_PATH = SCHEMA_DIR / "tenant-blueprint.schema.json"


DEFAULT_SYSTEM_SETTINGS: dict[str, Any] = {
    "deployment": {
        "mode": "local-first-dfy",
        "licenseModel": "one-pay",
        "tenantBlueprintsEnabled": True,
        "handoffCapable": True,
    },
    "ui": {
        "defaultTheme": "auto",
    },
    "internal": {
        "environmentLabel": "production-local",
        "metadata": {},
    },
}


DEFAULT_TENANT_SETTINGS: dict[str, Any] = {
    "branding": {
        "theme": "auto",
        "layout": "sidebar-left",
        "brandName": "AIO CRM",
        "companyName": "AIO CRM",
        "companyLogo": "",
        "logoUrl": "/aio-button-192px.png",
        "primaryColor": "#3b82f6",
        "secondaryColor": "#1e40af",
        "accentColor": "#8b5cf6",
        "menuBackgroundColor": "var(--color-bg-primary)",
        "menuTextColor": "var(--color-text-primary)",
        "footerText": "Generated by Cortex",
        "disclaimer": "Confidential - Internal Use Only",
        "contactInfo": "",
        "reportHeaderLabel": "Cortex Intelligence Report",
    },
    "navigation": {
        # `null` means navigation has not been configured yet.
        # `[]` means an intentionally empty navigation was saved.
        "menuStructure": None,
        "mobileItems": [],
    },
    "globalVariables": {},
    "domains": {
        "primaryDomain": "",
        "allowedDomains": [],
    },
    "comms": {
        "defaults": {
            "defaultMailboxId": "",
            "defaultAssignee": "",
            "defaultFromName": "",
            "defaultReplyTo": "",
            "signature": "",
        },
        "systemEmailTemplates": {},
    },
    "calendar": {
        "defaults": {
            "defaultCalendarId": "",
            "defaultBookingTypeId": "",
            "defaultMeetingDuration": 30,
            "defaultEventDurationMinutes": 30,
            "defaultLocationType": "other",
            "defaultLocationValue": "",
            "bufferBeforeMinutes": 0,
            "bufferAfterMinutes": 0,
        },
    },
    "automation": {
        "defaults": {
            "enabled": True,
            "approvalMode": "standard",
        },
    },
    "visibility": {
        "hiddenModules": [],
        "clientEditableSections": [],
    },
    "internal": {
        # Operational tenant metadata only. Identity/index fields such as id/name/slug
        # remain authoritative on the tenant row and must not be duplicated here.
        "clientLabel": "",
        "deploymentTag": "",
        "handoffStatus": "internal",
        "notes": "",
        "metadata": {},
    },
}


DEFAULT_USER_SETTINGS: dict[str, Any] = {
    "preferences": {
        "theme": "auto",
        "locale": "en-US",
        "timezone": "America/New_York",
    },
    "profile": {
        "phone": "",
    },
    "comms": {
        "emailSignature": "",
    },
    "internal": {
        "metadata": {},
    },
}


FIELD_POLICIES: dict[str, Any] = {
    "tenant": {
        # `tenant.settings` remains the compatibility view used by the current frontend.
        # Canonical data lives in tenantSettings, with selected legacy aliases projected from it.
        "compatibilityAliases": {
            "menu_structure": "navigation.menuStructure",
        },
        "derivedPaths": [
            "globalVariables",
            "comms.systemEmailTemplates",
        ],
    },
    "user": {
        "derivedPaths": [
            "profile.phone",
            "preferences.locale",
            "preferences.timezone",
            "comms.emailSignature",
        ],
    },
    "blueprint": {
        "excludedPaths": [
            "sessions",
            "passwords",
            "user",
            "audit",
            "runtime",
        ],
    },
}


BLUEPRINT_SECTION_KEYS = [
    "branding",
    "navigation",
    "globalVariables",
    "domains",
    "comms",
    "calendar",
    "automation",
    "visibility",
    "internal",
]


TENANT_INTERNAL_RESERVED_IDENTITY_KEYS = {
    "id",
    "name",
    "slug",
    "tenantId",
    "tenant_id",
    "workspaceId",
    "workspace_id",
}


def load_schema(schema_path: str | Path) -> dict[str, Any]:
    path = Path(schema_path)
    return json.loads(path.read_text(encoding="utf-8"))


def _deepcopy(value: Any) -> Any:
    return copy.deepcopy(value)


def merge_with_defaults(defaults: Any, value: Any) -> Any:
    if isinstance(defaults, dict):
        merged = {key: _deepcopy(item) for key, item in defaults.items()}
        if not isinstance(value, dict):
            return merged
        for key, item in value.items():
            if key in merged:
                merged[key] = merge_with_defaults(merged[key], item)
            else:
                merged[key] = _deepcopy(item)
        return merged
    if isinstance(defaults, list):
        return _deepcopy(value if isinstance(value, list) else defaults)
    return _deepcopy(defaults if value is None else value)


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _unwrap_container(payload: dict[str, Any], *keys: str) -> dict[str, Any]:
    for key in keys:
        value = payload.get(key)
        if isinstance(value, dict):
            return value
    return payload


def _normalize_navigation(candidate: dict[str, Any]) -> dict[str, Any]:
    navigation = candidate.get("navigation") if isinstance(candidate.get("navigation"), dict) else {}
    # Preserve the canonical contract:
    # `menuStructure: null` = unconfigured, `[]` = intentionally empty, non-empty array = configured.
    if "menu_structure" in candidate:
        menu_structure = candidate.get("menu_structure")
        if menu_structure is None or isinstance(menu_structure, list):
            navigation = {**navigation, "menuStructure": menu_structure}
    return navigation


def _normalize_tenant_internal(candidate: dict[str, Any]) -> dict[str, Any]:
    internal = candidate.get("internal")
    if not isinstance(internal, dict):
        return {}
    return {
        key: value
        for key, value in internal.items()
        if key not in TENANT_INTERNAL_RESERVED_IDENTITY_KEYS
    }


def normalize_system_settings_payload(payload: dict[str, Any] | None, *, include_defaults: bool = False) -> dict[str, Any]:
    candidate = _unwrap_container(payload or {}, "systemSettings", "system")
    normalized = candidate if isinstance(candidate, dict) else {}
    return merge_with_defaults(DEFAULT_SYSTEM_SETTINGS, normalized) if include_defaults else normalized


def normalize_tenant_settings_payload(payload: dict[str, Any] | None, *, include_defaults: bool = False) -> dict[str, Any]:
    candidate = _unwrap_container(payload or {}, "tenantSettings", "tenant")
    if not isinstance(candidate, dict):
        candidate = {}

    normalized: dict[str, Any] = {}
    for key in ["branding", "globalVariables", "domains", "comms", "calendar", "automation", "visibility"]:
        if isinstance(candidate.get(key), dict):
            normalized[key] = candidate[key]
    internal = _normalize_tenant_internal(candidate)
    if internal:
        normalized["internal"] = internal
    navigation = _normalize_navigation(candidate)
    if navigation:
        normalized["navigation"] = navigation
    if "mobileItems" in candidate and isinstance(candidate.get("mobileItems"), list):
        navigation = normalized.get("navigation") if isinstance(normalized.get("navigation"), dict) else {}
        navigation["mobileItems"] = candidate["mobileItems"]
        normalized["navigation"] = navigation
    return merge_with_defaults(DEFAULT_TENANT_SETTINGS, normalized) if include_defaults else normalized


def normalize_user_settings_payload(payload: dict[str, Any] | None, *, include_defaults: bool = False) -> dict[str, Any]:
    candidate = _unwrap_container(payload or {}, "userSettings", "user")
    normalized = candidate if isinstance(candidate, dict) else {}
    return merge_with_defaults(DEFAULT_USER_SETTINGS, normalized) if include_defaults else normalized


def tenant_settings_to_legacy_view(tenant_settings: dict[str, Any]) -> dict[str, Any]:
    compatibility = _deepcopy(tenant_settings)
    navigation = compatibility.get("navigation") if isinstance(compatibility.get("navigation"), dict) else {}
    if "menuStructure" in navigation and (navigation.get("menuStructure") is None or isinstance(navigation.get("menuStructure"), list)):
        compatibility["menu_structure"] = navigation.get("menuStructure")
    return compatibility


def strip_derived_tenant_sections(tenant_settings: dict[str, Any]) -> dict[str, Any]:
    persisted = normalize_tenant_settings_payload(tenant_settings, include_defaults=True)
    persisted["globalVariables"] = {}
    comms = persisted.get("comms") if isinstance(persisted.get("comms"), dict) else {}
    comms["systemEmailTemplates"] = {}
    persisted["comms"] = comms
    return persisted


def _coerce_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value.astimezone(UTC) if value.tzinfo else value.replace(tzinfo=UTC)
    raw = str(value).strip()
    if not raw:
        return None
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return None
    return parsed.astimezone(UTC) if parsed.tzinfo else parsed.replace(tzinfo=UTC)


def calendar_defaults_from_tenant_settings(tenant_settings: dict[str, Any] | None) -> dict[str, Any]:
    normalized = normalize_tenant_settings_payload({"tenantSettings": tenant_settings or {}}, include_defaults=True)
    calendar = normalized.get("calendar") if isinstance(normalized.get("calendar"), dict) else {}
    defaults = calendar.get("defaults") if isinstance(calendar.get("defaults"), dict) else {}
    duration_minutes = _safe_int(
        defaults.get("defaultMeetingDuration", defaults.get("defaultEventDurationMinutes", 30)),
        30,
    )
    return {
        **defaults,
        "defaultMeetingDuration": duration_minutes,
        "defaultEventDurationMinutes": duration_minutes,
        "defaultCalendarId": str(defaults.get("defaultCalendarId") or "").strip(),
        "defaultBookingTypeId": str(defaults.get("defaultBookingTypeId") or "").strip(),
        "defaultLocationType": str(defaults.get("defaultLocationType") or "other").strip() or "other",
        "defaultLocationValue": str(defaults.get("defaultLocationValue") or "").strip(),
        "bufferBeforeMinutes": _safe_int(defaults.get("bufferBeforeMinutes"), 0),
        "bufferAfterMinutes": _safe_int(defaults.get("bufferAfterMinutes"), 0),
    }


def apply_calendar_event_defaults(payload: dict[str, Any] | None, tenant_settings: dict[str, Any] | None) -> dict[str, Any]:
    resolved = dict(payload or {})
    defaults = calendar_defaults_from_tenant_settings(tenant_settings)
    applied_defaults: dict[str, Any] = {}

    if not resolved.get("calendar_id") and defaults["defaultCalendarId"]:
        resolved["calendar_id"] = defaults["defaultCalendarId"]
        applied_defaults["defaultCalendarId"] = defaults["defaultCalendarId"]
    if not resolved.get("booking_type_id") and defaults["defaultBookingTypeId"]:
        resolved["booking_type_id"] = defaults["defaultBookingTypeId"]
        applied_defaults["defaultBookingTypeId"] = defaults["defaultBookingTypeId"]
    if not resolved.get("location_type") and defaults["defaultLocationType"]:
        resolved["location_type"] = defaults["defaultLocationType"]
        applied_defaults["defaultLocationType"] = defaults["defaultLocationType"]
    if not resolved.get("location") and defaults["defaultLocationValue"]:
        resolved["location"] = defaults["defaultLocationValue"]
        applied_defaults["defaultLocationValue"] = defaults["defaultLocationValue"]

    duration_minutes = defaults["defaultMeetingDuration"]
    buffer_before = defaults["bufferBeforeMinutes"]
    buffer_after = defaults["bufferAfterMinutes"]
    start_dt = _coerce_datetime(resolved.get("start_time"))
    end_dt = _coerce_datetime(resolved.get("end_time"))
    total_minutes = duration_minutes + buffer_before + buffer_after

    if start_dt is None and end_dt is None:
        start_dt = datetime.now(UTC)
        end_dt = start_dt + timedelta(minutes=total_minutes)
        resolved["start_time"] = start_dt.isoformat()
        resolved["end_time"] = end_dt.isoformat()
        applied_defaults["defaultMeetingDuration"] = duration_minutes
        applied_defaults["bufferBeforeMinutes"] = buffer_before
        applied_defaults["bufferAfterMinutes"] = buffer_after
    elif start_dt is not None and end_dt is None:
        end_dt = start_dt + timedelta(minutes=total_minutes)
        resolved["end_time"] = end_dt.isoformat()
        applied_defaults["defaultMeetingDuration"] = duration_minutes
        applied_defaults["bufferBeforeMinutes"] = buffer_before
        applied_defaults["bufferAfterMinutes"] = buffer_after
    elif start_dt is None and end_dt is not None:
        start_dt = end_dt - timedelta(minutes=total_minutes)
        resolved["start_time"] = start_dt.isoformat()
        applied_defaults["defaultMeetingDuration"] = duration_minutes
        applied_defaults["bufferBeforeMinutes"] = buffer_before
        applied_defaults["bufferAfterMinutes"] = buffer_after

    if applied_defaults:
        source_payload = resolved.get("source_payload") if isinstance(resolved.get("source_payload"), dict) else {}
        source_payload["calendar_defaults"] = applied_defaults
        resolved["source_payload"] = source_payload
    return resolved


def build_settings_bundle(system_settings: dict[str, Any], tenant_settings: dict[str, Any], user_settings: dict[str, Any]) -> dict[str, Any]:
    return {
        "systemSettings": merge_with_defaults(DEFAULT_SYSTEM_SETTINGS, system_settings),
        "tenantSettings": merge_with_defaults(DEFAULT_TENANT_SETTINGS, tenant_settings),
        "userSettings": merge_with_defaults(DEFAULT_USER_SETTINGS, user_settings),
        "fieldPolicies": _deepcopy(FIELD_POLICIES),
    }


def _expected_types(type_name: str) -> tuple[type[Any], ...]:
    mapping: dict[str, tuple[type[Any], ...]] = {
        "object": (dict,),
        "array": (list,),
        "string": (str,),
        "boolean": (bool,),
        "integer": (int,),
        "number": (int, float),
        "null": (type(None),),
    }
    return mapping.get(type_name, (object,))


def _matches_type(value: Any, schema_type: str) -> bool:
    if schema_type == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if schema_type == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    return isinstance(value, _expected_types(schema_type))


def _validate_node(value: Any, schema: dict[str, Any], path: str, errors: list[str]) -> None:
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        if not any(_matches_type(value, item) for item in schema_type):
            errors.append(f"{path}: expected one of {schema_type}, got {type(value).__name__}")
            return
    elif isinstance(schema_type, str) and not _matches_type(value, schema_type):
        errors.append(f"{path}: expected {schema_type}, got {type(value).__name__}")
        return

    if schema.get("type") == "object" or (isinstance(schema.get("type"), list) and "object" in schema.get("type") and isinstance(value, dict)):
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        for key in required:
            if key not in value:
                errors.append(f"{path}.{key}: missing required field")
        additional_allowed = schema.get("additionalProperties", True)
        for key, item in value.items():
            if key in properties:
                _validate_node(item, properties[key], f"{path}.{key}", errors)
            elif isinstance(additional_allowed, dict):
                _validate_node(item, additional_allowed, f"{path}.{key}", errors)
            elif additional_allowed is False:
                errors.append(f"{path}.{key}: additional property is not allowed")
        return

    if schema.get("type") == "array" and isinstance(value, list):
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for index, item in enumerate(value):
                _validate_node(item, item_schema, f"{path}[{index}]", errors)


def validate_against_schema(schema_name: str, payload: dict[str, Any]) -> tuple[bool, list[str]]:
    schema_path = TENANT_SETTINGS_SCHEMA_PATH if schema_name == "tenant-settings" else TENANT_BLUEPRINT_SCHEMA_PATH
    schema = load_schema(schema_path)
    errors: list[str] = []
    _validate_node(payload, schema, "$", errors)
    return not errors, errors


def export_tenant_blueprint(
    tenant_settings: dict[str, Any],
    *,
    flows: list[dict[str, Any]] | None = None,
    blueprint_id: str | None = None,
    name: str | None = None,
    description: str | None = None,
    source: str | None = None,
    version: str | int | None = None,
) -> dict[str, Any]:
    normalized = normalize_tenant_settings_payload(tenant_settings, include_defaults=True)
    variables = normalized.get("globalVariables") if isinstance(normalized.get("globalVariables"), dict) else {}
    sanitized_variables: dict[str, Any] = {}
    for variable_key, variable in variables.items():
        if not isinstance(variable, dict):
            continue
        sanitized_variables[variable_key] = {
            key: _deepcopy(value)
            for key, value in variable.items()
            if key != "id"
        }
    normalized["globalVariables"] = sanitized_variables
    comms = normalized.get("comms") if isinstance(normalized.get("comms"), dict) else {}
    templates = comms.get("systemEmailTemplates") if isinstance(comms.get("systemEmailTemplates"), dict) else {}
    sanitized_templates: dict[str, Any] = {}
    for template_key, template in templates.items():
        if not isinstance(template, dict):
            continue
        sanitized_templates[template_key] = {
            "templateKey": template.get("templateKey") or template_key,
            "emailType": template.get("emailType") or template_key.replace("_", " ").title(),
            "subject": template.get("subject") or "",
            "sendTo": template.get("sendTo") or "",
            "enabled": bool(template.get("enabled", True)),
            "bodyHtml": template.get("bodyHtml"),
            "bodyText": template.get("bodyText"),
            "config": template.get("config") or {},
        }
    comms["systemEmailTemplates"] = sanitized_templates
    normalized["comms"] = comms
    blueprint = {
        "blueprintId": blueprint_id or (normalized.get("internal") or {}).get("blueprintId") or "tenant-export",
        "name": name or "Tenant Export",
        "description": description or "Portable tenant blueprint export.",
        "version": version or 1,
        "source": source or "tenant-export",
        "blueprintVersion": 1,
        "tenant": {key: _deepcopy(normalized.get(key)) for key in BLUEPRINT_SECTION_KEYS},
        "flows": _deepcopy(flows or []),
        "fieldPolicies": _deepcopy(FIELD_POLICIES),
    }
    return blueprint


def import_tenant_blueprint(blueprint: dict[str, Any]) -> dict[str, Any]:
    tenant_payload = blueprint.get("tenant") if isinstance(blueprint.get("tenant"), dict) else blueprint
    return normalize_tenant_settings_payload({"tenant": tenant_payload}, include_defaults=True)
