import React from 'react';
import { FileText, Calendar, Building2, Cpu } from 'lucide-react';
import { DEFAULT_BRAND_CONFIG } from '../contexts/BrandContext';

const ReportLetterheadTemplate = ({ 
  brandConfig = DEFAULT_BRAND_CONFIG,
  reportMeta = {},
  reportBody = '',
  isFallback = false
}) => {
  const {
    brandName = 'AIO CRM',
    logoUrl = '/aio-button-192px.png',
    primaryColor = '#3b82f6',
    footerText = 'Generated by Cortex',
    disclaimer = 'Confidential - Internal Use Only',
    contactInfo = '',
    reportHeaderLabel = 'Cortex Intelligence Report'
  } = brandConfig;

  const {
    reportTitle = 'Intelligence Report',
    reportType = '',
    generatedAt = new Date().toISOString(),
    accountName = ''
  } = reportMeta;

  const formatDate = (isoString) => {
    try {
      return new Date(isoString).toLocaleString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch {
      return isoString;
    }
  };

  const sanitizeContent = (content) => {
    if (!content) return '';
    return content
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\n/g, '<br/>');
  };

  return (
    <div className="bg-white text-slate-900 font-sans rounded-xl overflow-hidden shadow-xl max-w-4xl mx-auto">
      {/* Header */}
      <div 
        className="px-8 py-6 border-b-2"
        style={{ borderColor: primaryColor }}
      >
        <div className="flex items-start justify-between">
          {/* Logo + Brand */}
          <div className="flex items-center gap-4">
            {logoUrl && (
              <img 
                src={logoUrl} 
                alt={brandName}
                className="w-12 h-12 rounded-lg object-contain"
                onError={(e) => { e.target.style.display = 'none'; }}
              />
            )}
            <div>
              <h1 className="text-xl font-bold text-slate-900">{brandName}</h1>
              <p className="text-xs text-slate-500 uppercase tracking-wider">{reportHeaderLabel}</p>
            </div>
          </div>

          {/* Report Info */}
          <div className="text-right space-y-1">
            <div className="flex items-center gap-2 justify-end text-slate-600">
              <FileText size={14} />
              <span className="text-sm font-medium">{reportTitle}</span>
            </div>
            {reportType && (
              <div className="text-xs text-slate-500 uppercase tracking-wide">
                {reportType}
              </div>
            )}
          </div>
        </div>

        {/* Meta Row */}
        <div className="mt-6 flex items-center gap-6 text-xs text-slate-500 border-t border-slate-200 pt-4">
          <div className="flex items-center gap-1.5">
            <Calendar size={12} />
            <span>{formatDate(generatedAt)}</span>
          </div>
          {accountName && (
            <div className="flex items-center gap-1.5">
              <Building2 size={12} />
              <span>{accountName}</span>
            </div>
          )}
          <div className="flex items-center gap-1.5">
            <Cpu size={12} />
            <span>AIO Cortex</span>
          </div>
        </div>

        {/* Fallback Badge */}
        {isFallback && (
          <div className="mt-4 inline-flex items-center gap-2 px-3 py-1 bg-amber-50 border border-amber-200 rounded-full">
            <span className="text-xs font-medium text-amber-700">Fallback Report (Template Generated)</span>
          </div>
        )}
      </div>

      {/* Divider */}
      <div 
        className="h-1"
        style={{ backgroundColor: primaryColor }}
      />

      {/* Report Body */}
      <div className="px-8 py-6 min-h-[300px]">
        <div 
          className="prose prose-slate max-w-none text-sm text-slate-700 leading-relaxed whitespace-pre-wrap"
          dangerouslySetInnerHTML={{ __html: sanitizeContent(reportBody) }}
        />
      </div>

      {/* Footer */}
      <div className="px-8 py-4 bg-slate-50 border-t border-slate-200">
        <div className="flex items-start justify-between text-xs text-slate-500">
          <div className="space-y-1">
            {footerText && (
              <p className="font-medium">{footerText}</p>
            )}
            {disclaimer && (
              <p className="text-slate-400 italic">{disclaimer}</p>
            )}
            {contactInfo && (
              <p className="text-slate-400">{contactInfo}</p>
            )}
          </div>
          <div className="text-right">
            <p className="text-slate-400">
              Report generated by <span className="font-medium">AIO Cortex</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportLetterheadTemplate;
