import {
  draftAiApi,
  getOperatorAssistResponseApi,
  runAiCommandApi,
  getAiRunsApi,
  getAiRunApi,
  getAiAgentsApi,
  updateAiAgentApi,
  getSystemHealthApi,
  getAiProviderCatalogApi,
  getOllamaModelsApi,
  getAiProviderConfigsApi,
  upsertAiProviderConfigApi,
  deleteAiProviderConfigApi,
  testAiProviderConfigApi,
  getWorkspacesApi,
  createWorkspaceApi,
  updateWorkspaceApi,
  deleteWorkspaceApi,
  getWorkspaceMembershipsApi,
  addWorkspaceMemberApi,
  createWorkspaceUserApi,
  updateWorkspaceMemberApi,
  removeWorkspaceMemberApi,
  getWorkspaceRolesApi,
  createWorkspaceRoleApi,
  updateWorkspaceRoleApi,
  attachWorkspaceRoleApi,
  detachWorkspaceRoleApi,
  request,
} from './backendApi';

export const AiService = {
  draftAi: (payload) => draftAiApi(payload),
  getOperatorAssistResponse: (payload) => getOperatorAssistResponseApi(payload),
  runAiCommand: (payload) => runAiCommandApi(payload),
  getAiRuns: (limit, flowId) => getAiRunsApi(limit, flowId),
  getAiRun: (runId) => getAiRunApi(runId),
  getAiAgents: (includeHidden) => getAiAgentsApi(includeHidden),
  updateAiAgent: (agentKey, payload) => updateAiAgentApi(agentKey, payload),
  getSystemHealth: () => getSystemHealthApi(),
  getAiProviderCatalog: () => getAiProviderCatalogApi(),
  getOllamaModels: (payload) => getOllamaModelsApi(payload),
  getAiProviderConfigs: () => getAiProviderConfigsApi(),
  upsertAiProviderConfig: (providerKey, payload) => upsertAiProviderConfigApi(providerKey, payload),
  deleteAiProviderConfig: (configId) => deleteAiProviderConfigApi(configId),
  testAiProviderConfig: (configId) => testAiProviderConfigApi(configId),
  getWorkspaces: () => getWorkspacesApi(),
  createWorkspace: (payload) => createWorkspaceApi(payload),
  updateWorkspace: (workspaceId, payload) => updateWorkspaceApi(workspaceId, payload),
  deleteWorkspace: (workspaceId) => deleteWorkspaceApi(workspaceId),
  getWorkspaceMemberships: (workspaceId) => getWorkspaceMembershipsApi(workspaceId),
  addWorkspaceMember: (workspaceId, payload) => addWorkspaceMemberApi(workspaceId, payload),
  createWorkspaceUser: (workspaceId, payload) => createWorkspaceUserApi(workspaceId, payload),
  updateWorkspaceMember: (workspaceId, membershipId, payload) => updateWorkspaceMemberApi(workspaceId, membershipId, payload),
  removeWorkspaceMember: (workspaceId, membershipId) => removeWorkspaceMemberApi(workspaceId, membershipId),
  getWorkspaceRoles: (workspaceId) => getWorkspaceRolesApi(workspaceId),
  createWorkspaceRole: (workspaceId, payload) => createWorkspaceRoleApi(workspaceId, payload),
  updateWorkspaceRole: (workspaceId, roleId, payload) => updateWorkspaceRoleApi(workspaceId, roleId, payload),
  attachWorkspaceRole: (workspaceId, roleId, payload) => attachWorkspaceRoleApi(workspaceId, roleId, payload),
  detachWorkspaceRole: (workspaceId, roleId, entityType, entityId) => detachWorkspaceRoleApi(workspaceId, roleId, entityType, entityId),
  sendVttCommand: (payload) => request('/api/vtt/command', { method: 'POST', body: JSON.stringify(payload) }),
  sendAiCommandRaw: (payload) => request('/api/ai/command', { method: 'POST', body: JSON.stringify(payload) }),
};