import {
  getBrainOverviewApi,
  getBrainProfileApi,
  updateBrainProfileApi,
  getBrainSourcesApi,
  createBrainSourceApi,
  updateBrainSourceApi,
  deleteBrainSourceApi,
  getBrainItemsApi,
  createBrainItemApi,
  updateBrainItemApi,
  deleteBrainItemApi,
  getBrainLinksApi,
  createBrainLinkApi,
  deleteBrainLinkApi,
  getBrainIngestsApi,
  createBrainIngestApi,
  probeBrainMcpApi,
  queryBrainMcpApi,
  searchBrainMemoryApi,
  saveTranscriptApi,
} from './backendApi';

export const BrainService = {
  getBrainOverview: () => getBrainOverviewApi(),
  getBrainProfile: () => getBrainProfileApi(),
  updateBrainProfile: (payload) => updateBrainProfileApi(payload),
  getBrainSources: () => getBrainSourcesApi(),
  createBrainSource: (payload) => createBrainSourceApi(payload),
  updateBrainSource: (sourceId, payload) => updateBrainSourceApi(sourceId, payload),
  deleteBrainSource: (sourceId) => deleteBrainSourceApi(sourceId),
  getBrainItems: () => getBrainItemsApi(),
  createBrainItem: (payload) => createBrainItemApi(payload),
  updateBrainItem: (itemId, payload) => updateBrainItemApi(itemId, payload),
  deleteBrainItem: (itemId) => deleteBrainItemApi(itemId),
  getBrainLinks: () => getBrainLinksApi(),
  createBrainLink: (payload) => createBrainLinkApi(payload),
  deleteBrainLink: (linkId) => deleteBrainLinkApi(linkId),
  getBrainIngests: (sourceId, limit) => getBrainIngestsApi(sourceId, limit),
  createBrainIngest: (payload) => createBrainIngestApi(payload),
  probeBrainMcp: (sourceId) => probeBrainMcpApi(sourceId),
  queryBrainMcp: (sourceId, payload) => queryBrainMcpApi(sourceId, payload),
  searchBrainMemory: (query, limit, options) => searchBrainMemoryApi(query, limit, options),
  saveTranscript: (payload) => saveTranscriptApi(payload),
};