import {
  getCalendarsApi,
  getCalendarEventsApi,
  createCalendarEventApi,
  updateCalendarEventApi,
  deleteCalendarEventApi,
  pushCalendarEventApi,
  reconcileCalendarEventApi,
  getCalendarSourcesApi,
  getCalendarProvidersApi,
  createCalendarSourceApi,
  updateCalendarSourceApi,
  listCalendarSourceCalendarsApi,
  deleteCalendarSourceApi,
  disconnectCalendarSourceApi,
  testCalendarSourceApi,
  syncCalendarSourceApi,
  importCalendarSourceApi,
  getCalendarSourceAuthorizeUrl,
  getBookingTypesApi,
  createBookingTypeApi,
  updateBookingTypeApi,
  deleteBookingTypeApi,
} from './backendApi';

export const CalendarService = {
  getCalendars: () => getCalendarsApi(),
  getCalendarEvents: () => getCalendarEventsApi(),
  createCalendarEvent: (payload) => createCalendarEventApi(payload),
  updateCalendarEvent: (eventId, payload) => updateCalendarEventApi(eventId, payload),
  deleteCalendarEvent: (eventId) => deleteCalendarEventApi(eventId),
  pushCalendarEvent: (eventId, sourceId) => pushCalendarEventApi(eventId, sourceId),
  reconcileCalendarEvent: (eventId, strategy) => reconcileCalendarEventApi(eventId, strategy),
  getCalendarSources: () => getCalendarSourcesApi(),
  getCalendarProviders: () => getCalendarProvidersApi(),
  createCalendarSource: (payload) => createCalendarSourceApi(payload),
  updateCalendarSource: (sourceId, payload) => updateCalendarSourceApi(sourceId, payload),
  listCalendarSourceCalendars: (sourceId) => listCalendarSourceCalendarsApi(sourceId),
  deleteCalendarSource: (sourceId, fallbackSourceId) => deleteCalendarSourceApi(sourceId, fallbackSourceId),
  disconnectCalendarSource: (sourceId) => disconnectCalendarSourceApi(sourceId),
  testCalendarSource: (sourceId) => testCalendarSourceApi(sourceId),
  syncCalendarSource: (sourceId) => syncCalendarSourceApi(sourceId),
  importCalendarSource: (sourceId) => importCalendarSourceApi(sourceId),
  getCalendarSourceAuthorizeUrl: (sourceId) => getCalendarSourceAuthorizeUrl(sourceId),
  getBookingTypes: () => getBookingTypesApi(),
  createBookingType: (payload) => createBookingTypeApi(payload),
  updateBookingType: (bookingTypeId, payload) => updateBookingTypeApi(bookingTypeId, payload),
  deleteBookingType: (bookingTypeId) => deleteBookingTypeApi(bookingTypeId),
};