import {
  getCommsSnapshotApi,
  createThreadApi,
  openThreadForContactApi,
  sendThreadMessageApi,
  sendThreadEmailApi,
  updateThreadStatusApi,
  assignThreadApi,
  updateThreadMailboxApi,
  summarizeThreadApi,
  createThreadDraftApi,
  createDealFromThreadApi,
  advanceThreadStageApi,
  scheduleThreadMeetingApi,
  createThreadReportApi,
  deleteThreadApi,
  getCommsOverviewApi,
  getPhoneNumbersApi,
  createPhoneNumberApi,
  updatePhoneNumberApi,
  deletePhoneNumberApi,
  getSmsThreadsApi,
  createSmsThreadApi,
  addSmsMessageApi,
  getSmsPlansApi,
  createSmsPlanApi,
  updateSmsPlanApi,
  getSmsThreadApi,
  getSmsMessagesApi,
  sendSmsApi,
  checkOptOutApi,
  getContactsWithPhoneApi,
  getExtensionsApi,
  createExtensionApi,
  getRingGroupsApi,
  createRingGroupApi,
  getCallSessionsApi,
  createCallSessionApi,
  updateCallSessionApi,
  startOutboundCallApi,
  endCallSessionApi,
  getCallSessionApi,
  getCommsRoutesApi,
  getCommsContactSummaryApi,
  createCommsActivityApi,
  getCommsIntegrationInfoApi,
  getCommsProviderConfigsApi,
  saveCommsProviderConfigApi,
  verifyCommsProviderConfigApi,
  deleteCommsProviderConfigApi,
  getMailboxesApi,
  createMailboxApi,
  getMailboxProvidersApi,
  updateMailboxApi,
  deleteMailboxApi,
  disconnectMailboxApi,
  getMailboxEventsApi,
  syncMailboxApi,
  testMailboxConnectionApi,
  getMailboxAuthorizeUrl,
  ingestMailboxMessageApi,
} from './backendApi';

export const CommsService = {
  getCommsSnapshot: () => getCommsSnapshotApi(),
  createThread: (payload) => createThreadApi(payload),
  openThreadForContact: (payload) => openThreadForContactApi(payload),
  sendThreadMessage: (threadId, payload) => sendThreadMessageApi(threadId, payload),
  sendThreadEmail: (threadId, payload) => sendThreadEmailApi(threadId, payload),
  updateThreadStatus: (threadId, status) => updateThreadStatusApi(threadId, status),
  assignThread: (threadId, assigneeName) => assignThreadApi(threadId, assigneeName),
  updateThreadMailbox: (threadId, mailboxId) => updateThreadMailboxApi(threadId, mailboxId),
  summarizeThread: (threadId) => summarizeThreadApi(threadId),
  createThreadDraft: (threadId, mode) => createThreadDraftApi(threadId, mode),
  createDealFromThread: (threadId) => createDealFromThreadApi(threadId),
  advanceThreadStage: (threadId) => advanceThreadStageApi(threadId),
  scheduleThreadMeeting: (threadId, scheduledAt) => scheduleThreadMeetingApi(threadId, scheduledAt),
  createThreadReport: (threadId, kind) => createThreadReportApi(threadId, kind),
  deleteThread: (threadId) => deleteThreadApi(threadId),
  getCommsOverview: () => getCommsOverviewApi(),
  getPhoneNumbers: () => getPhoneNumbersApi(),
  createPhoneNumber: (payload) => createPhoneNumberApi(payload),
  updatePhoneNumber: (numberId, payload) => updatePhoneNumberApi(numberId, payload),
  deletePhoneNumber: (numberId) => deletePhoneNumberApi(numberId),
  getSmsThreads: (limit) => getSmsThreadsApi(limit),
  createSmsThread: (payload) => createSmsThreadApi(payload),
  addSmsMessage: (threadId, payload) => addSmsMessageApi(threadId, payload),
  getSmsPlans: () => getSmsPlansApi(),
  createSmsPlan: (payload) => createSmsPlanApi(payload),
  updateSmsPlan: (planId, payload) => updateSmsPlanApi(planId, payload),
  getSmsThread: (threadId) => getSmsThreadApi(threadId),
  getSmsMessages: (threadId) => getSmsMessagesApi(threadId),
  sendSms: (payload) => sendSmsApi(payload),
  checkOptOut: (phoneNumber) => checkOptOutApi(phoneNumber),
  getContactsWithPhone: () => getContactsWithPhoneApi(),
  getExtensions: () => getExtensionsApi(),
  createExtension: (payload) => createExtensionApi(payload),
  getRingGroups: () => getRingGroupsApi(),
  createRingGroup: (payload) => createRingGroupApi(payload),
  getCallSessions: (limit) => getCallSessionsApi(limit),
  createCallSession: (payload) => createCallSessionApi(payload),
  updateCallSession: (sessionId, payload) => updateCallSessionApi(sessionId, payload),
  startOutboundCall: (payload) => startOutboundCallApi(payload),
  endCallSession: (callId, payload) => endCallSessionApi(callId, payload),
  getCallSession: (callId) => getCallSessionApi(callId),
  getCommsRoutes: () => getCommsRoutesApi(),
  getCommsContactSummary: (contactId) => getCommsContactSummaryApi(contactId),
  createCommsActivity: (payload) => createCommsActivityApi(payload),
  getCommsIntegrationInfo: () => getCommsIntegrationInfoApi(),
  getCommsProviderConfigs: () => getCommsProviderConfigsApi(),
  saveCommsProviderConfig: (providerType, config, isActive) => saveCommsProviderConfigApi(providerType, config, isActive),
  verifyCommsProviderConfig: (providerType, config) => verifyCommsProviderConfigApi(providerType, config),
  deleteCommsProviderConfig: (providerType) => deleteCommsProviderConfigApi(providerType),
  getMailboxes: () => getMailboxesApi(),
  createMailbox: (payload) => createMailboxApi(payload),
  getMailboxProviders: () => getMailboxProvidersApi(),
  updateMailbox: (mailboxId, payload) => updateMailboxApi(mailboxId, payload),
  deleteMailbox: (mailboxId, fallbackMailboxId) => deleteMailboxApi(mailboxId, fallbackMailboxId),
  disconnectMailbox: (mailboxId) => disconnectMailboxApi(mailboxId),
  getMailboxEvents: (mailboxId) => getMailboxEventsApi(mailboxId),
  syncMailbox: (mailboxId) => syncMailboxApi(mailboxId),
  testMailboxConnection: (mailboxId) => testMailboxConnectionApi(mailboxId),
  getMailboxAuthorizeUrl: (mailboxId) => getMailboxAuthorizeUrl(mailboxId),
  ingestMailboxMessage: (mailboxId, payload) => ingestMailboxMessageApi(mailboxId, payload),
};