import {
  getContactsApi,
  createContactApi,
  updateContactApi,
  deleteContactApi,
  restoreContactApi,
  listDeletedContactsApi,
  bulkDeleteContactsApi,
  getContactActivitiesApi,
  createContactActivityApi,
  getContactFormSubmissionsApi,
  getCompaniesApi,
  getCompanyApi,
  updateCompanyApi,
  getTagsApi,
  createTagApi,
  updateTagApi,
  deleteTagApi,
  validateTagFormat,
  CANONICAL_TAG_PREFIXES,
  getCmsTablesApi,
  getCmsTableDataApi,
  toSnakeCase,
} from './backendApi';

export { toSnakeCase };

export const CrmService = {
  getContacts: () => getContactsApi(),
  createContact: (payload) => createContactApi(payload),
  updateContact: (contactId, payload) => updateContactApi(contactId, payload),
  deleteContact: (contactId) => deleteContactApi(contactId),
  restoreContact: (contactId) => restoreContactApi(contactId),
  listDeletedContacts: () => listDeletedContactsApi(),
  bulkDeleteContacts: (ids) => bulkDeleteContactsApi(ids),
  getContactActivities: (contactId) => getContactActivitiesApi(contactId),
  createContactActivity: (contactId, payload) => createContactActivityApi(contactId, payload),
  getContactFormSubmissions: (contactId) => getContactFormSubmissionsApi(contactId),
  getCompanies: () => getCompaniesApi(),
  getCompany: (companyId) => getCompanyApi(companyId),
  updateCompany: (companyId, payload) => updateCompanyApi(companyId, payload),
  getTags: (prefix) => getTagsApi(prefix),
  createTag: (payload) => createTagApi(payload),
  updateTag: (tagId, updates) => updateTagApi(tagId, updates),
  deleteTag: (tagId) => deleteTagApi(tagId),
  validateTagFormat,
  CANONICAL_TAG_PREFIXES,
  getCmsTables: () => getCmsTablesApi(),
  getCmsTableData: (slug) => getCmsTableDataApi(slug),
};