import {
  getGlobalVariablesApi,
  getCanonicalSettingsApi,
  updateCanonicalTenantSettingsApi,
  upsertGlobalVariableApi,
  deleteGlobalVariableApi,
  getSystemEmailTemplatesApi,
  updateSystemEmailTemplateApi,
  getWorkspacesApi,
  createWorkspaceApi,
  updateWorkspaceApi,
  deleteWorkspaceApi,
  getWorkspaceMembershipsApi,
  getUserAccessApi,
  addWorkspaceMemberApi,
  createWorkspaceUserApi,
  updateWorkspaceMemberApi,
  removeWorkspaceMemberApi,
  getWorkspaceRolesApi,
  createWorkspaceRoleApi,
  updateWorkspaceRoleApi,
  attachWorkspaceRoleApi,
  detachWorkspaceRoleApi,
  getEmailVerifierConfigApi,
  updateEmailVerifierConfigApi,
  testEmailVerifierConfigApi,
  deleteEmailVerifierConfigApi,
  verifyEmailApi,
  createEmailVerificationBulkTaskApi,
  getEmailVerificationBulkTaskApi,
  getDataStoreProviderConfigsApi,
  upsertDataStoreProviderConfigApi,
  deleteDataStoreProviderConfigApi,
  testDataStoreProviderConfigApi,
  readDataStoreRecordsApi,
  createDataStoreRecordApi,
  updateDataStoreRecordApi,
  upsertDataStoreRecordApi,
} from './backendApi';

export const SettingsService = {
  getGlobalVariables: () => getGlobalVariablesApi(),
  getCanonicalSettings: () => getCanonicalSettingsApi(),
  updateCanonicalTenantSettings: (settings) => updateCanonicalTenantSettingsApi(settings),
  upsertGlobalVariable: (payload) => upsertGlobalVariableApi(payload),
  deleteGlobalVariable: (variableId) => deleteGlobalVariableApi(variableId),
  getSystemEmailTemplates: (search) => getSystemEmailTemplatesApi(search),
  updateSystemEmailTemplate: (templateId, payload) => updateSystemEmailTemplateApi(templateId, payload),
  getWorkspaces: () => getWorkspacesApi(),
  createWorkspace: (payload) => createWorkspaceApi(payload),
  updateWorkspace: (workspaceId, payload) => updateWorkspaceApi(workspaceId, payload),
  deleteWorkspace: (workspaceId) => deleteWorkspaceApi(workspaceId),
  getWorkspaceMemberships: (workspaceId) => getWorkspaceMembershipsApi(workspaceId),
  getUserAccess: (email) => getUserAccessApi(email),
  addWorkspaceMember: (workspaceId, payload) => addWorkspaceMemberApi(workspaceId, payload),
  createWorkspaceUser: (workspaceId, payload) => createWorkspaceUserApi(workspaceId, payload),
  updateWorkspaceMember: (workspaceId, membershipId, payload) => updateWorkspaceMemberApi(workspaceId, membershipId, payload),
  removeWorkspaceMember: (workspaceId, membershipId) => removeWorkspaceMemberApi(workspaceId, membershipId),
  getWorkspaceRoles: (workspaceId) => getWorkspaceRolesApi(workspaceId),
  createWorkspaceRole: (workspaceId, payload) => createWorkspaceRoleApi(workspaceId, payload),
  updateWorkspaceRole: (workspaceId, roleId, payload) => updateWorkspaceRoleApi(workspaceId, roleId, payload),
  attachWorkspaceRole: (workspaceId, roleId, payload) => attachWorkspaceRoleApi(workspaceId, roleId, payload),
  detachWorkspaceRole: (workspaceId, roleId, entityType, entityId) => detachWorkspaceRoleApi(workspaceId, roleId, entityType, entityId),
  getEmailVerifierConfig: () => getEmailVerifierConfigApi(),
  updateEmailVerifierConfig: (payload) => updateEmailVerifierConfigApi(payload),
  testEmailVerifierConfig: () => testEmailVerifierConfigApi(),
  deleteEmailVerifierConfig: () => deleteEmailVerifierConfigApi(),
  verifyEmail: (payload) => verifyEmailApi(payload),
  createEmailVerificationBulkTask: (payload) => createEmailVerificationBulkTaskApi(payload),
  getEmailVerificationBulkTask: (taskId) => getEmailVerificationBulkTaskApi(taskId),
  getDataStoreProviderConfigs: () => getDataStoreProviderConfigsApi(),
  upsertDataStoreProviderConfig: (providerKey, payload) => upsertDataStoreProviderConfigApi(providerKey, payload),
  deleteDataStoreProviderConfig: (providerKey) => deleteDataStoreProviderConfigApi(providerKey),
  testDataStoreProviderConfig: (providerKey) => testDataStoreProviderConfigApi(providerKey),
  readDataStoreRecords: (providerKey, payload) => readDataStoreRecordsApi(providerKey, payload),
  createDataStoreRecord: (providerKey, payload) => createDataStoreRecordApi(providerKey, payload),
  updateDataStoreRecord: (providerKey, payload) => updateDataStoreRecordApi(providerKey, payload),
  upsertDataStoreRecord: (providerKey, payload) => upsertDataStoreRecordApi(providerKey, payload),
};