const textField = (name, label, extras = {}) => ({
  type: 'text',
  name,
  label,
  required: false,
  isContent: false,
  ...extras,
});

const emailField = (name = 'email', label = 'Email Address', extras = {}) => ({
  type: 'email',
  name,
  label,
  required: true,
  mapToContact: 'email',
  isIdentifier: true,
  isContent: false,
  ...extras,
});

const telField = (name = 'phone', label = 'Phone Number', extras = {}) => ({
  type: 'tel',
  name,
  label,
  mapToContact: 'phone',
  isContent: false,
  ...extras,
});

const textareaField = (name, label, extras = {}) => ({
  type: 'textarea',
  name,
  label,
  required: false,
  isContent: true,
  ...extras,
});

const selectField = (name, label, options, extras = {}) => ({
  type: 'select',
  name,
  label,
  options,
  required: false,
  isContent: false,
  ...extras,
});

export const formTemplates = [
  {
    id: 'lead-intake',
    name: 'Lead Intake',
    category: 'Lead Capture',
    description: 'Capture net-new leads with contact details, qualification signals, and the primary request.',
    complexity: 'Basic',
    fields: [
      textField('firstName', 'First Name', { required: true, mapToContact: 'firstName' }),
      textField('lastName', 'Last Name', { required: true, mapToContact: 'lastName' }),
      emailField(),
      telField(),
      textField('companyName', 'Company Name'),
      textareaField('primaryNeed', 'What Do You Need Help With?'),
    ],
  },
  {
    id: 'client-intake',
    name: 'Client Intake',
    category: 'Client Intake',
    description: 'Collect onboarding context, scope, goals, and operating details from a new client.',
    complexity: 'Intermediate',
    fields: [
      textField('firstName', 'First Name', { required: true, mapToContact: 'firstName' }),
      textField('lastName', 'Last Name', { required: true, mapToContact: 'lastName' }),
      emailField(),
      telField(),
      textField('businessName', 'Business Name', { required: true }),
      textareaField('engagementScope', 'Engagement Scope', { required: true }),
      textareaField('currentChallenges', 'Current Challenges'),
      textareaField('successMetrics', 'Success Metrics'),
      textareaField('additionalContext', 'Additional Context'),
    ],
  },
  {
    id: 'business-dna-intake',
    name: 'Business DNA Intake',
    category: 'Business DNA',
    description: 'Mirror the current Brain-side identity, mission, audience, and market intake structure without direct writeback.',
    complexity: 'Advanced',
    fields: [
      textField('companyName', 'Business Name', { required: true }),
      textField('brandVoice', 'Brand Voice'),
      textareaField('valueProp', 'Value Proposition', { required: true }),
      textareaField('mission', 'Mission Statement', { required: true }),
      textareaField('differentiation', 'Differentiators'),
      textareaField('idealCustomer', 'Ideal Customer'),
      textareaField('painPoints', 'Pain Points'),
      textareaField('competitors', 'Competitor Landscape'),
      textareaField('marketingStrategy', 'Marketing Strategy'),
      textareaField('workflow', 'Operational Workflow'),
    ],
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    category: 'Lead Capture',
    description: 'Simple contact capture for public-facing reach-outs and routing.',
    complexity: 'Basic',
    fields: [
      textField('fullName', 'Full Name', { required: true, mapToContact: 'fullName' }),
      emailField(),
      telField(),
      textareaField('message', 'Message', { required: true }),
    ],
  },
  {
    id: 'appointment-booking-intake',
    name: 'Appointment / Booking Intake',
    category: 'Booking',
    description: 'Collect scheduling preferences and context before routing to a calendar or operator.',
    complexity: 'Intermediate',
    fields: [
      textField('fullName', 'Full Name', { required: true, mapToContact: 'fullName' }),
      emailField('workEmail', 'Work Email'),
      telField(),
      selectField('meetingType', 'Meeting Type', ['Consultation', 'Demo', 'Onboarding', 'Support']),
      selectField('timeline', 'Preferred Timeline', ['This Week', 'Next Week', 'This Month', 'Flexible']),
      textareaField('agendaNotes', 'Agenda Notes'),
    ],
  },
  {
    id: 'survey-feedback',
    name: 'Survey / Feedback',
    category: 'Feedback',
    description: 'Capture structured feedback with a rating plus qualitative comments.',
    complexity: 'Basic',
    fields: [
      textField('fullName', 'Full Name', { mapToContact: 'fullName' }),
      emailField(),
      selectField('satisfactionLevel', 'Satisfaction Level', ['Excellent', 'Good', 'Average', 'Poor'], { required: true }),
      textareaField('whatWorkedWell', 'What Worked Well?'),
      textareaField('improvementNotes', 'What Should Improve?'),
    ],
  },
  {
    id: 'application-form',
    name: 'Application Form',
    category: 'Applications',
    description: 'Collect applicant identity, background, and motivation in a structured format.',
    complexity: 'Advanced',
    fields: [
      textField('firstName', 'First Name', { required: true }),
      textField('lastName', 'Last Name', { required: true }),
      emailField(),
      telField(),
      textField('linkedinUrl', 'LinkedIn URL'),
      textareaField('experienceSummary', 'Experience Summary', { required: true }),
      textareaField('whyYouAreApplying', 'Why Are You Applying?', { required: true }),
    ],
  },
  {
    id: 'funnel-qualification-form',
    name: 'Funnel / Qualification Form',
    category: 'Qualification',
    description: 'Qualify deal readiness with role, stage, budget, and timing signals.',
    complexity: 'Intermediate',
    fields: [
      textField('fullName', 'Full Name', { required: true, mapToContact: 'fullName' }),
      emailField(),
      textField('companyName', 'Company Name'),
      textField('roleTitle', 'Role Title'),
      selectField('budgetRange', 'Budget Range', ['Under $1k', '$1k-$5k', '$5k-$20k', '$20k+']),
      selectField('decisionTimeline', 'Decision Timeline', ['Immediate', '30 Days', '60 Days', '90+ Days']),
      textareaField('primaryChallenge', 'Primary Challenge'),
    ],
  },
  {
    id: 'content-intake',
    name: 'Content Intake',
    category: 'Content',
    description: 'Collect campaign goals, audience context, and core messaging for content production.',
    complexity: 'Intermediate',
    fields: [
      textField('requestTitle', 'Request Title', { required: true }),
      selectField('contentType', 'Content Type', ['Email', 'Landing Page', 'Video Script', 'Ad Copy', 'Blog Post'], { required: true }),
      textareaField('campaignGoal', 'Campaign Goal', { required: true }),
      textareaField('audienceProfile', 'Audience Profile'),
      textareaField('keyMessage', 'Key Message'),
      textareaField('callToActionStyle', 'Call To Action Style'),
      textareaField('referenceLinks', 'Reference Links'),
      textareaField('additionalContext', 'Additional Context'),
    ],
  },
  {
    id: 'event-registration',
    name: 'Event Registration',
    category: 'Events',
    description: 'Capture registrant details, attendance preferences, and event-specific notes.',
    complexity: 'Basic',
    fields: [
      textField('firstName', 'First Name', { required: true, mapToContact: 'firstName' }),
      textField('lastName', 'Last Name', { required: true, mapToContact: 'lastName' }),
      emailField(),
      telField(),
      selectField('attendanceType', 'Attendance Type', ['In Person', 'Virtual'], { required: true }),
      textareaField('accessibilityNotes', 'Accessibility Notes'),
    ],
  },
  {
    id: 'newsletter-signup',
    name: 'Newsletter Signup',
    category: 'Lead Capture',
    description: 'Collect a lightweight subscription profile for newsletters and updates.',
    complexity: 'Basic',
    fields: [
      textField('fullName', 'Full Name', { mapToContact: 'fullName' }),
      emailField(),
      selectField('interestArea', 'Interest Area', ['Product Updates', 'Events', 'Offers', 'Education']),
      textareaField('topicsOfInterest', 'Topics Of Interest'),
    ],
  },
  {
    id: 'partner-intake',
    name: 'Partner Intake',
    category: 'Partnerships',
    description: 'Qualify strategic partner opportunities with fit, reach, and collaboration goals.',
    complexity: 'Intermediate',
    fields: [
      textField('contactName', 'Contact Name', { required: true }),
      emailField('businessEmail', 'Business Email'),
      textField('companyName', 'Company Name', { required: true }),
      textField('partnershipType', 'Partnership Type'),
      textareaField('audienceOverlap', 'Audience Overlap'),
      textareaField('proposedCollaboration', 'Proposed Collaboration'),
    ],
  },
  {
    id: 'creative-brief',
    name: 'Creative Brief',
    category: 'Content',
    description: 'Capture the strategic brief for creative production without adding separate workflow logic.',
    complexity: 'Advanced',
    fields: [
      textField('projectName', 'Project Name', { required: true }),
      selectField('deliverableType', 'Deliverable Type', ['Landing Page', 'Ad Creative', 'Email', 'Video', 'Social']),
      textareaField('businessObjective', 'Business Objective', { required: true }),
      textareaField('audienceInsight', 'Audience Insight'),
      textareaField('toneDirection', 'Tone Direction'),
      textareaField('requiredAssets', 'Required Assets'),
    ],
  },
  {
    id: 'exit-survey',
    name: 'Exit Survey',
    category: 'Feedback',
    description: 'Collect final-stage sentiment, reasons for churn, and recovery signals.',
    complexity: 'Intermediate',
    fields: [
      textField('fullName', 'Full Name'),
      emailField(),
      selectField('outcomeStatus', 'Outcome Status', ['Completed', 'Cancelled', 'Paused', 'Churned'], { required: true }),
      textareaField('reasonForLeaving', 'Reason For Leaving', { required: true }),
      textareaField('whatCouldImprove', 'What Could Improve'),
    ],
  },
  {
    id: 'demo-request',
    name: 'Demo Request',
    category: 'Booking',
    description: 'Qualify inbound demo interest before routing to calendar and CRM.',
    complexity: 'Intermediate',
    fields: [
      textField('fullName', 'Full Name', { required: true, mapToContact: 'fullName' }),
      emailField('workEmail', 'Work Email'),
      textField('companyName', 'Company Name', { required: true }),
      selectField('teamSize', 'Team Size', ['1-10', '11-50', '51-200', '200+']),
      textareaField('primaryGoal', 'Primary Goal'),
    ],
  },
  {
    id: 'support-request',
    name: 'Support Request',
    category: 'Support',
    description: 'Route support tickets with clear issue and urgency capture.',
    complexity: 'Intermediate',
    fields: [
      textField('fullName', 'Full Name', { required: true, mapToContact: 'fullName' }),
      emailField(),
      selectField('urgency', 'Urgency', ['Low', 'Normal', 'High', 'Critical'], { required: true }),
      textareaField('issueSummary', 'Issue Summary', { required: true }),
    ],
  },
  {
    id: 'order-form',
    name: 'Order Form',
    category: 'Orders',
    description: 'Collect purchase details with contact and fulfillment inputs.',
    complexity: 'Advanced',
    fields: [
      textField('customerName', 'Customer Name', { required: true }),
      emailField(),
      telField(),
      textField('shippingAddress', 'Shipping Address', { type: 'address', required: true }),
      textareaField('orderNotes', 'Order Notes'),
    ],
  },
];

export const formTemplateCategories = ['All', ...new Set(formTemplates.map((template) => template.category))];
