import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const generateBrandId = () => {
  return `brand_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
};

export const DEFAULT_BRAND_CONFIG = {
  brandId: null,
  brandName: 'AIO CRM',
  logoUrl: '/aio-button-192px.png',
  primaryColor: '#3b82f6',
  secondaryColor: '#1e40af',
  accentColor: '#8b5cf6',
  footerText: 'Generated by Cortex',
  disclaimer: 'Confidential - Internal Use Only',
  contactInfo: '',
  reportHeaderLabel: 'Cortex Intelligence Report',
  templateType: 'standard'
};

const STORAGE_KEY = 'aio_brand_config';

const loadBrandConfig = () => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      return { ...DEFAULT_BRAND_CONFIG, ...JSON.parse(saved) };
    }
  } catch (e) {
    console.warn('[BrandContext] Failed to load brand config');
  }
  return { ...DEFAULT_BRAND_CONFIG };
};

const saveBrandConfig = (config) => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
  } catch (e) {
    console.warn('[BrandContext] Failed to save brand config');
  }
};

const BrandContext = createContext(null);

export const useBrand = () => {
  const context = useContext(BrandContext);
  if (!context) {
    return { 
      brandConfig: DEFAULT_BRAND_CONFIG, 
      setBrandConfig: () => {},
      resetBrandConfig: () => {},
      resolveBrandConfig: () => DEFAULT_BRAND_CONFIG
    };
  }
  return context;
};

export const BrandProvider = ({ children, initialConfig = {} }) => {
  const [brandConfig, setBrandConfigState] = useState(() => {
    const loaded = loadBrandConfig();
    
    if (!loaded.brandId) {
      loaded.brandId = generateBrandId();
      saveBrandConfig(loaded);
    }
    
    return {
      ...DEFAULT_BRAND_CONFIG,
      ...loaded,
      ...initialConfig
    };
  });

  const setBrandConfig = useCallback((updates) => {
    setBrandConfigState(prev => {
      const updated = typeof updates === 'function' ? updates(prev) : { ...prev, ...updates };
      
      if (!updated.brandId) {
        updated.brandId = generateBrandId();
      }
      
      saveBrandConfig(updated);
      return updated;
    });
  }, []);

  const resetBrandConfig = useCallback(() => {
    const fresh = { 
      ...DEFAULT_BRAND_CONFIG, 
      brandId: generateBrandId() 
    };
    saveBrandConfig(fresh);
    setBrandConfigState(fresh);
  }, []);

  const resolveBrandConfig = useCallback((tenantConfig = null, workspaceConfig = null) => {
    const resolutionOrder = [
      tenantConfig,
      workspaceConfig,
      brandConfig,
      DEFAULT_BRAND_CONFIG
    ];

    const resolved = { ...DEFAULT_BRAND_CONFIG };
    
    for (const config of resolutionOrder) {
      if (config && typeof config === 'object') {
        Object.assign(resolved, config);
      }
    }
    
    if (!resolved.brandId) {
      resolved.brandId = generateBrandId();
    }
    
    return resolved;
  }, [brandConfig]);

  useEffect(() => {
    const loaded = loadBrandConfig();
    if (loaded.brandId && loaded.brandId !== brandConfig.brandId) {
      setBrandConfigState(prev => ({ ...prev, ...loaded }));
    }
  }, []);

  return (
    <BrandContext.Provider value={{ 
      brandConfig, 
      setBrandConfig, 
      resetBrandConfig,
      resolveBrandConfig
    }}>
      {children}
    </BrandContext.Provider>
  );
};

export const getBrandConfig = () => {
  return loadBrandConfig();
};

export default BrandContext;
