import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const generateBrandId = () => {
  return `brand_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
};

export const DEFAULT_BRAND_CONFIG = {
  brandId: null,
  brandName: 'AIO CRM',
  logoUrl: '/aio-button-192px.png',
  primaryColor: '#3b82f6',
  secondaryColor: '#1e40af',
  accentColor: '#8b5cf6',
  footerText: 'Generated by Cortex',
  disclaimer: 'Confidential - Internal Use Only',
  contactInfo: '',
  reportHeaderLabel: 'Cortex Intelligence Report',
  templateType: 'standard'
};

const BrandContext = createContext(null);

export const useBrand = () => {
  const context = useContext(BrandContext);
  if (!context) {
    return { 
      brandConfig: DEFAULT_BRAND_CONFIG, 
      setBrandConfig: () => {},
      resetBrandConfig: () => {},
      resolveBrandConfig: () => DEFAULT_BRAND_CONFIG
    };
  }
  return context;
};

export const BrandProvider = ({ children, initialConfig = {} }) => {
  const [brandConfig, setBrandConfigState] = useState(() => {
    return {
      ...DEFAULT_BRAND_CONFIG,
      ...initialConfig,
      brandId: initialConfig?.brandId || generateBrandId(),
    };
  });

  useEffect(() => {
    setBrandConfigState((current) => ({
      ...current,
      ...DEFAULT_BRAND_CONFIG,
      ...initialConfig
    }));
  }, [initialConfig]);

  const setBrandConfig = useCallback((updates) => {
    setBrandConfigState(prev => {
      const updated = typeof updates === 'function' ? updates(prev) : { ...prev, ...updates };
      
      if (!updated.brandId) {
        updated.brandId = generateBrandId();
      }
      return updated;
    });
  }, []);

  const resetBrandConfig = useCallback(() => {
    const fresh = { 
      ...DEFAULT_BRAND_CONFIG, 
      brandId: generateBrandId() 
    };
    setBrandConfigState(fresh);
  }, []);

  const resolveBrandConfig = useCallback((tenantConfig = null, workspaceConfig = null) => {
    const resolutionOrder = [
      tenantConfig,
      workspaceConfig,
      brandConfig,
      DEFAULT_BRAND_CONFIG
    ];

    const resolved = { ...DEFAULT_BRAND_CONFIG };
    
    for (const config of resolutionOrder) {
      if (config && typeof config === 'object') {
        Object.assign(resolved, config);
      }
    }
    
    if (!resolved.brandId) {
      resolved.brandId = generateBrandId();
    }
    
    return resolved;
  }, [brandConfig]);
  return (
    <BrandContext.Provider value={{ 
      brandConfig, 
      setBrandConfig, 
      resetBrandConfig,
      resolveBrandConfig
    }}>
      {children}
    </BrandContext.Provider>
  );
};

export const getBrandConfig = () => {
  return { ...DEFAULT_BRAND_CONFIG };
};

export default BrandContext;
